let email=document.getElementById("email")
let password=document.getElementById("Password")
console.log(email.innerText)
console.log(password.value)
document.getElementById("submit").addEventListener("click",function())